### ISSUE TITLE
Public Intersect Town Hall Planning Workgroup session 2 - June 13th  2024

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Intersect-Town-Hall#12]
# Workshop Purpose: 
> Workgroup helps to Co-Create and Operate Intersect Town Halls
# Meeting notes: 
https://miro.com/app/board/uXjVKG5h5BA=/?moveToWidget=3458764591648778412&cot=10

# Meeting Summary 

# People Present:

Tevo [facilitator], Stephen [facilitator], Felix [facilitator], Vani [facilitator], Abe Ellis [participant], Samuel Hogan [participant], Nicodemus Rodriguez [participant]

# Community Problem Board
## Discussion Points
- https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/24
- https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/31
- https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/32 
- https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/30 

# Town Hall Structure and Introductory Material
## Decision items
- https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/35

## Action Items
- https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/36
- https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/37
- Create an infographic of the Town Hall structure ?
- https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/38
# Town Hall Agenda
## Discussion Points
Problem Board Issue: 
- https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/32
- What Should be this month's Town Hall agenda?
- How do we approach creating agendas for Town Halls?
- Marketing Workgroup can help us publicize information
- Who is our target audience now and later?
- We note that we shouldn’t provide the Intersect team with the agenda too early - it needs to be after both of our community planning sessions have taken place, so there is time for proper community input
## Action Items
- https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/39
# After Town Hall Agenda
## Discussion Points
Problem Board Issue: 
- https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/30
- What break-out room topics should we have?
- What break-out rooms should we run?
- What do we know about the Constitution Committee?
- Should there be a maximum number of breakout rooms each time, so we don’t end up with only a couple of people in each one? Max 4, first come first served?
- Is TH more of a “governance” space, and ATH more of a “community-building” one?

## Action Items
- For the first TH, we will organize a few breakout rooms just for people who have already expressed interest; plus, we will run one ourselves
- After that, we will create and publicize a sign-up process
- Find people who are interested in sharing the work they do in Intersect

------------

## Proposal context
https://catalyst-swarm.gitbook.io/intersect-town-hall-playbook/proposal-reporting/the-proposal/intersect-town-hall-by-swarm

### Acceptance Criteria

> Facilitate a session

**Comment by whitevo** [comment]
Meeting Summary: https://docs.google.com/document/d/1RzC2CRxSNJty8FFum0KBJ0hgO_60Srjveb5BcLn4hoo/edit?usp=sharing
