### ISSUE TITLE
Action - Intersect Discord Channel Setup

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Intersect-Town-Hall#21]
- [x] Setup Swarm Project Management channel
- [x] Setup Intersect Town Hall channel - to be created in Town Square section 
- [x] Resolve event calendar access (Access given to Swarm for townhalls@intersectmbo.org)

**Comment by whitevo** [comment]
Channel Created
https://discord.com/channels/1136727663583698984/1245340231482474506

**Comment by whitevo** [comment]
We have the all the access and everything is set up , but chronicle bot breaks to include in Discord Events.
