### ISSUE TITLE
how do we reach people who don't attend TH?

### ISSUE THREAD

**Issue by VanCardui** [Catalyst-Swarm/Intersect-Town-Hall#27]
### Source:
Town Hall #1, Thurs 6th June 2024

### Problem
We don't know how to reach those who are Intersect members but not very involved at all; and those who *are* active, but don't come to TH

**Comment by VanCardui** [comment]
### Current situation
- Some active Intersect members who engage in working groups etc, don't attend TH or ATH
- Some people are members, but are not active at all.
- The Intersect Team is in the process of creating a list of members

### How we want the current situation to change:
- People who are active e.g. in working groups and on Discord and/or Twitter will get involved in Town Hall
- Intersect members who are not involved at all will feel welcome and will join TH and ATH

### Who are the stakeholders?
-

### Any previous attempts to address this problem?
- 

### Questions and possible approaches:
- Should we expect to see people at TH and ATH who are not yet involved at all?
- Should we expect to be able to involve people who are active in WGs?
- Are there any issues with contacting people and asking them to get involved?
- How should we contact them?
- Can we ping specific workgroups in Discord? How are Discord roles used?
- Do we need clarity in TH and ATH on whose voices are Intersect Team members, and whose are "the community"?

### Ideas:
- Intersect members list, when done, could be made accessible to the Town Hall Workgroup for sending surveys and for inviting to 1 to 1 calls?
- Most Discord roles are related to specific permissions and overall permissions; some roles are related to partner networks. Roles are meant to be general. To keep it simple, best not to introduce WG roles due to the large amount of them.
- Follow up on List Creation and provide a filter option: "Intersect Team members" and "community"? 

### Measure:
- numbers attending TH
- numbers attending ATH
- numbers facilitating an ATH
- numbers of people attending for the first time
- number of attendees who are not involved elsewhere in Intersect

**Comment by VanCardui** [comment]
1p1v nature of Google form!

**Comment by VanCardui** [comment]
We have an issue that we still don't know if we can have access to Intersect's list of members.
Without this, it will be impossible to reach the whole membership and find out why some do not attend TH.

So we need to redefine the issue to look at people who ARE active members of Intersect (so we can reach them) but don't attend TH.

We also might need to redefine the approach in terms of what we are asking - we shouldn't make assumptions about what people think about TH or even if they want/don't want one at all

Suggested approach is a Google form - draft is https://docs.google.com/forms/d/e/1FAIpQLSeubRX9-_1dIzkdtmhG3692LsUnBuKttRQWNMNAMeb9fdNJ2g/viewform?usp=sharing

**Comment by VanCardui** [comment]
Moving this issue back to "being worked on" now that we have redefined/clarified it a bit.

We can probably only reach poeple who don't attend TH but *are* involved in Intersect in some way, since it seems we cannot get access to Intersect's members list, even indirectly

**Comment by whitevo** [comment]
Intersect Staff has agreed to share the Intersect Town Hall survey through the Newsletter.
https://docs.google.com/forms/d/e/1FAIpQLSeubRX9-_1dIzkdtmhG3692LsUnBuKttRQWNMNAMeb9fdNJ2g/viewform

In addition, Intersect Staff is working on improving accessibility to different Intersect-related surveys.
