### ISSUE TITLE
We need to identify some breakout rooms for ATH

### ISSUE THREAD

**Issue by VanCardui** [Catalyst-Swarm/Intersect-Town-Hall#30]
### Source
Internal Swarm Team discussion on 13th June 2024

### Problem
We don't have any breakout rooms signed up for our first ATH.

**Comment by VanCardui** [comment]
### Current situation
- we have no breakout rooms agreed
- many people might not yet be aware what an ATH is and why they might want to do them
- we have not created a signup process

### How we want the current situation to change:
- sign up process created and publicised
- awareness raised about what ATHs are and why you might want to be part of them
- at least a couple of ATH breakout rooms identified for the first TH

### Who are the stakeholders?
-

### Any previous attempts to address this problem?
- 

### Questions and possible approaches:
- probably awareness can be built gradually, over a few weeks
- show why it's good by demonstrating? By having a couple of really interesting ones for the first TH
- Could the Swarm team run one to talk about our plans for TH? Is that interesting?
- Who could we approach to run one this month? Who is doing work that they might want to discuss?

### Ideas:
- 

### Measure:
- number of TH breakout rooms over the next 2 or 3 town halls

**Comment by VanCardui** [comment]
There's  been a Request from Samuel https://discord.com/channels/1136727663583698984/1245340231482474506/1250840797742366740 
_Can I get a breakout room dedicated to the election kickoff and public awareness? Ive been working with some folks in the Content Marketing Focus Group to build out materials we can roll out to the wider ecosystem, nft communities, discords, medium, educational courses, etc. Just need a place to talk about it_

WE should do one ourselves talking about ATH

Spotlight on someone's work - Tevo will invite some people.

Constitution - for next time? Adam Dean (@adamkdean on Twitter?)

should there be a limit to how many breakout rooms we have each session, to avoid dividing attention too much and ending up with only 3 people in a room? Should we say no more than 4 each time, first come - first served?

Need to share the signup process in in TH itself So we need to have that set up by then

**Comment by VanCardui** [comment]
On 27th June we held one "general" ATH breakout room, and one on the Constitution.
And we shared the signup form https://forms.gle/12WkPdaaS9vqg9pw9 
There have been no signups yet.

In planning meeting on 4th July, idea was suggested to directly contact organisations/teams/businesses building on Cardano and/or involved in Intersect and invite them to run a room

We could also approach different working groups and special interest groups

**Comment by VanCardui** [comment]
Ideas for 30th July:

**INO:** "how to approach creating a constitution" workshop
**Emanuele**: maybe an interview?

**How to reach Intersect members** - via Twitter? 
We'd send it to Lara and she can add it to comms plan.  
Swarm will prepare one, and tag Intersect to RT it. 
Invite people to submit ATH idea and give date of next TH

**Later: Tweet text sent to Lara by DM on Fri 12th July:**

_Want to run an After TownHall?
ATH is the after-party for Intersect Town Hall: breakout rooms, run by Intersect members, on topics they care about.

Next date: Thurs 25th July
Signup/details: https://forms.gle/69Qp7t49yZDF7R9z5
Support is available to plan & facilitate - ask in the form!_

**Comment by VanCardui** [comment]
In July, we had an ATH from ODIN. They plan to offer these regularly.
The INO room had to be cancelled, but INO are still keen to do one at a future TH. Tevo to liaise with them.

But we still haven't had any direct signups to the "book an ATH" form. How to address this?

- Need to Tweet it regularly
- Need Intersect team to amplify it, which they haven't done
- Need to reach out more to all the working groups and special interest groups - we probably need a simple mechanism to keep repeating this outreach (a weekly round of posting in Discord? Or better, invite community members to do it?)
- Need to fix the fact that on the Intersect site there is an alternative "sign up to do an ATH" which they still haven't taken down

**Comment by VanCardui** [comment]
If we do not get any further signups for one-off ATHs, do we need to move to having regular repeating ones instead?
Perhaps the idea of "Sign up to do an ATH" is not what people want.

ODIN is planning to offer a regular one
Should we (the Swarm team) aim to run one, perhaps as an Open Space where anyone can raise issues in an impromptu way?

We also perhaps need to find out more about why people are not signing up to run an ATH. A couple of people have said they are interested, but haven't actually signed up. 
 - can they find the form?
 - Do they need any support with planning, facilitating, etc?

**Comment by VanCardui** [comment]
- We need to hear back from Nana Safo on his planned ATH for September: Tevo has contacted him
- We also need to find out if the ATH signup form on the Intersect site can be removed - we have asked a couple of times, and no joy
- We could do with the Intersect team's support in sharing the form we are actually using.

**Comment by whitevo** [comment]
For the 24th Town Hall, Core Infrastructure Suppliers are available and would like to present a couple of slides about their work.
https://galois.com/project/blockchain-roundup/
