### ISSUE TITLE
We need to create some introductory materials for THs

### ISSUE THREAD

**Issue by VanCardui** [Catalyst-Swarm/Intersect-Town-Hall#31]
### Source
Internal discussion in Swarm team, 13th June 2024

### Problem
Each TH should begin with a clear and brief explanation of what TH is

**Comment by VanCardui** [comment]
### Current situation
- there is no introductory material to welcome people to TH and explain succinctly what it is

### How we want the current situation to change:
We need material that quickly and clearly answers the following
- What is Town Hall (TH)?
- Who Facilitate in Town Halls?
- Why do we have Town Halls?
- Why do we like to join Town Halls?
- What is After Town Hall (ATH)?
- Why do we like to join After Town Halls?
- Why do we have After Town Halls?
- How to submit Town Hall agendas?
- Where to submit questions for Town Hall?
- How to help or question prepared After Town Halls?

### Who are the stakeholders?
-

### Any previous attempts to address this problem?
- 

### Questions and possible approaches:
- What format should it be in? A script? A slide deck? Something else?
- Who will create it?

### Ideas:
- 

### Measure:
-

**Comment by VanCardui** [comment]
We will initially put the above list on a Google doc open to comments.
We create it - Nicodemus interested in editing - will share link in here
Deadline for comments is this day next week (20th June)

Abe will attach a file here with his own ideas on how it should go

NOTES:
It's attractive to attend if you know that every time you do, you get to take part in deciding the next tranche of questions about how we are going to refine it all - i.e. you are going to have the chance to vote on the next iteration. We need to design clear questions ahead of time and present them.

So it's a feedback loop for people to raise issues; a pathway for people to submit issues that others will vote on - like a change log, in effect. We ask people in a TH to define what the voting options should be.

We agree the introductory info should be presented as slides

Nicodemus and marketing group happy to help us get the info out!

[PipeDrive](https://www.pipedrive.com/) could help us get a grip on phases and cycles of development? 
We wouldn't use it cos not open source, but can we adapt ideas from how it woorks and apply them to our planning?

**Comment by whitevo** [comment]
Created the Google Doc under Swarm Account: https://docs.google.com/document/d/1wheIDiU9zlVui2bdXfEq9Wip2_C-CiOfaENoBH6S2to/edit?usp=sharing

**Comment by VanCardui** [comment]
Slides are here https://docs.google.com/presentation/d/1RURCxhUYcfNtGjXe2G_N1VXJ53Zifj-Ib9IqRD3EFNg/edit?usp=sharing

They can now be adapted each week

**Comment by whitevo** [comment]
> Slides are here https://docs.google.com/presentation/d/1RURCxhUYcfNtGjXe2G_N1VXJ53Zifj-Ib9IqRD3EFNg/edit?usp=sharing
> 
> They can now be adapted each week

it seems we need to use Intersect Team created slide templates Next Month

**Comment by VanCardui** [comment]
Vani will re-do the slides using the Intersect template

**Comment by VanCardui** [comment]
here are the new slides using Intersect template - https://docs.google.com/presentation/d/12oZ7jSuTko34hvfxY4bzVO0ygmutxNTUPfjJ-Qq7mIg/edit?usp=sharing

this issue feels "fixed", at least for now

**Comment by whitevo** [comment]
Yep we got no complaints this time.

The above template was copied to Swarm Drive and modified to fit the latest changes for the July 25th Town Hall
https://docs.google.com/presentation/d/1BEDX9XvaHdWeY-sy6Tq3BvcCzwlBzJnvt1-DbmIGE_k/edit?usp=sharing
