### ISSUE TITLE
We need to create an agenda for Town Hall

### ISSUE THREAD

**Issue by VanCardui** [Catalyst-Swarm/Intersect-Town-Hall#32]
### Source
Internal discussion in Swarm team, 13th June 2024

### Problem
There is no agenda yet for the first TH
We want to ensure it reflects what the community wants to discuss

**Comment by VanCardui** [comment]
### Current situation
- there is no agenda yet for our first TH

### How we want the current situation to change:
Create an agenda that reflects what the community wants to talk about 
and what the Swarm team needs to communicate

### Who are the stakeholders?
-

### Any previous attempts to address this problem?
- 

### Questions and possible approaches:
- First item should be the introductory material discussed in https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/31

### Ideas:
- 

### Measure:
- Qualitative measurement - did the agenda feel like it worked?
- Do we ned to improve it for next time?

**Comment by VanCardui** [comment]
We note that we shouldn’t provide the Intersect team with the agenda too early - it needs to be after both of our community planning sessions have taken place, so there is time for proper community input

The TH will start with the introductory material detailed here https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/31

what else should be on the agenda?

- Intro material on what TH is - slides
- Synopsis of what happened in last TH
- Results of polling info/community input during last TH
- What people are to vote on this time
- Share the signup process to run an ATH

- **Cardano’s constitution is i assume hot topic**
- Community Hubs have started
- share community problem board!
**- Updates from WGs?**
- Boilerplate "what is Intersect"?
- Spotlight - interesting stories - maybe invite people from the other IOG spotlight event?
- announcement of NFT-drop spaces
- Agenda needs to highlight ATH breakout rooms


You get more turnout when people know exactly what it's going to be about.

Marketing team to help us share the agenda in advance of the meeting
We have to take the info to them. 
Optics of sharing it with people rather than expecting them to come to us. - we need to make a point of sharing stuff and bring it to everyone.
Format to share the agenda - Twitter, Insta - and a more detailed format. Medium??
Discord Announcements?
Webhooks to share it in other Discords.

Scaleable way to do content creation - have an internal core set of content including re-useable stuff. Blog post synopses of what happened (this would be the equivalent of our GitBook summaries)

The "community" is everyone who holds ADA. Cardano has a duty to "be our megaphone"
Is the audience really all who have ADA? What is our goal, and what is our capacity

Core messaging that we can break up in to Tweets. Having that mechanism is importtant

Interesct members first, then other audience segments.

Analytics and tracking - collab on this with Marekting people!
Should someone else be paying for all this marketing?

Broadcast approach ties in with an open source approach. Layered info - ability to drill down

A funnel?? Drawing people in with increasing barriers of entry
Give aspotlight to regular projects that are doing cool stuff - do we need a separate event for that -  culture-building event.
Is a cultural event more of a one off? Nag, cos clture-building need s to be sustained
Hoiw does it scale tho?
maybe we get that community feel in ATH breakout rooms

Is TH a "governance meeting"?? 
separate the themes of governance, and ATH "share your cool stuff"

speed dating in TH, is it fun?   random pairs of people for 5 min for them to create strong links (what people do, where they parcipiate in intersect)

**Comment by whitevo** [comment]
Drafted Agenda Doc: https://docs.google.com/document/d/1BytbgGXHdtI8IHDRiyawwoPIpZqeyuc8i4Fx6ltL9Ek/edit

**Comment by VanCardui** [comment]
Feedback from Lara re the "human interface" game we played:

- People found it complicated to come back to the main room.
- Those in main room couldn't communicate with those in breakouts.

We just need to be a bit clearer about it.

Agenda for July TH https://docs.google.com/document/d/1h2H6VJ9eAsZNsZE4pBnAePx-NeSDNOOnEn-fz_7M-mI/edit?usp=sharing

**Comment by VanCardui** [comment]
Day of Town Hall - there has been publicity gone out that it's the 30th, so we need to correct that
Newsletter goes out on Friday - copy date is Thursday night.
We will write a correction

In future, TH will be 4th Thursday of the month, 16:00 UTC 
Vani to write 2 lines for newsletter and send to Lara tonight lara.bonasorte@intersectmbo.org


Later: Newsletter text is 

_**INTERSECT TOWN HALL DATE: CORRECTION!** 
You may have read that July's Intersect Town Hall is on Tues 30th July.  But there's been a change - the actual date is Thurs 25th July, 16:00 UTC.
For the future, Town Halls will always be on the 4th Thursday of the month: so 25th July, 22nd August, 26th September - all at 16:00 UTC

Sign up here https://us02web.zoom.us/meeting/register/tZEkc-ugqTIjE9zqEK2oRrfcltquGBPk_4v8 ; come and join us to share your updates, make connections, and come together as a community._

**Comment by VanCardui** [comment]
- The info on the date of TH has now been corrected in a newsletter. We need to continue to include an item reminding people of the date of TH, and the link to it, in subsequesnt newsletters.
- Our agenda for TH is now pretty fixed and regular - it will always be a variation on https://docs.google.com/presentation/d/1kczrgQ0tnQcrVN0g8k9Sqpgz0x6BzEzCo3GgD4zZZY8/edit?usp=sharing

When we share the agenda it needs to be succinct, but needs to include some specific detail about what's new each month - e.g. what the Zoom voting topic is, what the ATH rooms are.

However, sometimes we might not know ATH rooms until quite late

**Comment by VanCardui** [comment]
We now have an agenda structure, so it is just a matter now of collecting input in the form of slides each month

Generic agenda structure https://docs.google.com/document/d/1vyy2Ds3Y88YbNBVKMxCHOIk-0CNbCkhXbJkQ4tZi1MY/edit#heading=h.t8wrmopmsksn
