### ISSUE TITLE
Intersect Town Hall - 25th June 2024

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Intersect-Town-Hall#33]
This is the main tracking issue for the June 2024 Intersect Town Hall

# Slides

- https://docs.google.com/presentation/d/1RURCxhUYcfNtGjXe2G_N1VXJ53Zifj-Ib9IqRD3EFNg/edit?usp=sharing

# Sheet for collecting timestamps
- https://docs.google.com/spreadsheets/d/1VCAQDpT3vKrqf9MvwoApw5Z9TMkrtiM5PYaK_rfVolg/edit?usp=sharing

# Video
- https://www.youtube.com/watch?v=kN17feSQnVQ

# Actions
Related Actions include -

- https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/1
- https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/2
- https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/11

**Comment by stephen-rowan** [comment]
Actions arising from Problem Board
- https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/31

Create Action Item - Create Slides from this doc (Created the Google Doc under Swarm Account: https://docs.google.com/document/d/1wheIDiU9zlVui2bdXfEq9Wip2_C-CiOfaENoBH6S2to/edit?usp=sharing) - assigned to Vani

**Comment by whitevo** [comment]
In June, we started requesting permission to tag Intersect Members to amplify our outreach messages.
We also requested that they amplify messages for us if we are not allowed to tag everyone.

As of the due date, it still continues to be an issue where our requests do not get a reply.

**Comment by whitevo** [comment]
In June we had no access to appropriately update Google Calendar and Discord Events.
It was solved in the following month of July
