### ISSUE TITLE
Intersect After Town Hall - 25th June 2024

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Intersect-Town-Hall#34]
- https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/5
- https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/13
- https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/14
- https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/15
- https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/16

**Comment by whitevo** [comment]
In June, we started requesting permission to tag Intersect Members to amplify our outreach messages.
We also requested that they amplify messages for us if we are not allowed to tag everyone.

As of the due date, it still continues to be an issue where our requests do not get a reply.

**Comment by whitevo** [comment]
In June we had no access to appropriately update Google Calendar and Discord Events.
It was solved in the following month of July
