### ISSUE TITLE
Public Intersect Town Hall Planning Workgroup session 1 - Thursday 6th June 2024

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Intersect-Town-Hall#4]
This is the task issue for “Public Intersect Town Hall Planning Workgroup session 1 “ which was held on Thursday, 6th June 2024 at 1600 UTC.

This task is intended to

### Deliverable

- https://catalyst-swarm.gitbook.io/intersect-town-hall-playbook/the-proposal/intersect-town-hall-by-swarm

> 

### Acceptance Criteria

>.

### Estimated Duration 

>

### Cost

>

**Comment by whitevo** [comment]
Set up Town Hall WG Miro Board https://miro.com/app/board/uXjVKG5h5BA=/ with initial information and links to sources.

**Comment by stephen-rowan** [comment]
We need to work out how issues, subjects, concerns, topics etc are recorded on the problem board from each public planning meeting. 
- Draft Problem Board - https://github.com/orgs/Catalyst-Swarm/projects/2/views/1
- [ ] How to transfer issues to problem board from public meeting

The project tracking for this is here -
- https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/2

**Comment by stephen-rowan** [comment]
## Intersect Townhall Workgroup Meeting Overview
When: **06.06.2024 - 16:00 UTC**
Duration: ~90 min
Zoom: https://bit.ly/45bQrEr
Proposal: https://bit.ly/3Rct33S
Miro Board: https://bit.ly/4c4Htv0

### Context: 

Workgroup helps to Co-Create and Operate Intersect Townhalls
Parts of Sessions are recorded and uploaded to the Swarm YouTube channel
Miro Board is used for activities like meeting notes and information collection

### Workshop Agendas

- 5min - Welcome and Agenda
- 15min - Introduction to Townhall Workgroup (to be recorded)
- 10min - Collect Retrospective Information
- 30min - Discuss Retrospective points
- 25min - Open topics
- 5min - Session Overview (to be recorded)

**Comment by Technosophorso** [comment]
Some notes...
Many different areas clashing together, was hard to keep focus on Town Halls, we went about Governance & Discord servers, on knowledge management and marketing... seeing that it is not clear yet where the town halls sits, contributes and connects to the different areas. Will be a challenge to figure that out..., also on the "voice" of the town hall which should highlight Intersect community and less Intersect Management.. 

Suggestion was made to do a TH intro each time, on what & why TH.

**Comment by stephen-rowan** [comment]
Suggested regular time and dates for TH planning sessions is currently Thursdays at 1600 UTC

**Comment by whitevo** [comment]
Meeting Summary - https://docs.google.com/document/d/1jaaYIvVAGCM9rKkgpV7THvq0CCC6HcdeX-xYSAUB7u4/edit?usp=sharing
