### ISSUE TITLE
Public Intersect Town Hall Planning Workgroup session 2 - July 11th 2024

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Intersect-Town-Hall#41]
- [ ] Refer to Problems Board in summary in future
- [ ] Feed into GitBook as Playbook

## Intersect Town Hall Workgroup Meeting Overview
- When: 11.07.2024 - 16:00 UTC
- Duration: ~90 min
- Zoom: https://bit.ly/3W4tb8q
- Proposal: https://bit.ly/3Rct33S
- Miro Board: https://bit.ly/4c4Htv0
- GitHub Problem Board - https://github.com/orgs/Catalyst-Swarm/projects/2
- Context: Workgroup helps to Co-Create and Operate Intersect Town Halls
- Parts of Sessions are recorded and uploaded to the Swarm YouTube channel.
- Miro Board is used for activities like meeting notes and information collection.

## Suggested Workshop Agendas
- 5min - Welcome and Agenda
- 5min - (Optional) Introductions, Onboarding and Open Questions
- 20min - Review and Update Community Town Hall Problem Board
- 20min - Update Town Hall Agenda
- 15min - Coordinate After Town Hall Topics
- 10min - Decide on Intersect Town Hall date and time 
- 10min - Open Topics
- 5min - Session Overview (to be recorded)

## Previous planning meeting

- https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/40

This is the task issue for “Public Intersect Town Hall Planning Workgroup session 2“ which was held on 11th July 2024 at 1600 UTC.

## Last TH Slide deck: 

https://docs.google.com/presentation/d/1c-UQtW_Jdm5TPjgVScJFzQdEnRrbQn7TAucGm9LzBOw/edit#slide=id.g2e81879d9ac_0_21

## After Town Hall sign up form

-  https://forms.gle/jhomzjzXx9GQUWnx5

## Proposal context
- https://catalyst-swarm.gitbook.io/intersect-town-hall-playbook/the-proposal/intersect-town-hall-by-swarm

### Acceptance Criteria

> Facilitate and Document Workgroup Session

### Estimated Duration 

> Based on last month results it took about 5 hours to prepare
> This month it took 4 hours for this one and prolly for the next one
> The short-term goal is to get it down to 1-2 hours per person
> Meeting Summary usually takes under 2 hours, but this one was heavy one and don't know yet the after affects of using Git Hub as meeting summary drafting
> and the final component is facilitation time we do about 90min sessions

# Meeting notes: 
https://miro.com/app/board/uXjVKG5h5BA=/?moveToWidget=3458764593265587959&cot=10

# Meeting Summary 

# People Present:
Vani [facilitator], Tevo [facilitator], Stephen [facilitator], Can Huzmeli [participant], Emanuele Zanichelli [participant], Lara Bonasorte [participant]

# New joiners
- Can Huzmeli is part of technical operation team IOI which is related to IOG https://iohk.io/

# We need to identify some breakout rooms for ATH
## Discussion Points
- ATH Sign Up form has not submissions
- Reminders on previous suggestions
- How to reach Intersect members?
## Decision Items
- A topic about "How to prepare a meaningful Constitutional Workshop?" facilitated by INO
## Action Items
- Emanuele to coordinate an interview session
- Tevo to coordinate INO breakout room

# Intersect Town Hall Schedule
## Discussion Points
- When do we have Intersect Town Halls?
- When do Intersect Newsletters go out?
## Decision Items
- Town Halls will be on the 4th Thursday of the month, at 16:00 UTC
- Lara will support us in communicating the Town Hall Updates through the Newsletter and Twitter
## Action Items
- Inform Town Hall Date through the next Intersect Newsletter

# Zoom voting topic
## Discussion Points
- What questions should we ask?
- Do we want to quiz the audience for their understanding of Cardano or Intersect governance?
- What are conflicting questions we could ask where we will most likely see split of perspectives?
- How could we use the voting results?
- How topics and votes are stored?
- Who and how we decide on the voting topics?
- Do we want have poll about Governance Power?
## Decision Items
- We will do Zoom polling this Town Hall
## Action Items
- Draft questions for stand-up planning meetings to try

# Intersect Community Updates
## Discussion Points
- We don't have any updates from any of the committees, workgroups and sigs
- How do we gather information?
## Action Items
- Prepare a slide deck or a single slide where 1 liners could be added in
- Share the Slide and guidelines in each relevant channel to get information

# Permanent Intersect Team Updates
## Action Items
- Contact Lara, Nagatoshi and Jack again to coordinate topics for this month updates

**Comment by VanCardui** [comment]
Suggested agenda for 23rd July:
https://docs.google.com/document/d/1h2H6VJ9eAsZNsZE4pBnAePx-NeSDNOOnEn-fz_7M-mI/edit#heading=h.t8wrmopmsksn
