### ISSUE TITLE
Intersect Town Hall - 25th July 2024

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Intersect-Town-Hall#43]
This is the main tracking issue for the July 2024 Intersect Town Hall

# Slides

- https://docs.google.com/presentation/d/1BEDX9XvaHdWeY-sy6Tq3BvcCzwlBzJnvt1-DbmIGE_k/edit#slide=id.g26872c1a86d_0_0

# Sheet for collecting timestamps
- https://docs.google.com/spreadsheets/d/1VCAQDpT3vKrqf9MvwoApw5Z9TMkrtiM5PYaK_rfVolg/edit?gid=0#gid=0

> Same source will be used for both TH and ATH timestamps

# Video
- https://www.youtube.com/watch?v=2IaAIescVqg

# Actions
Related Actions include -
- Faciliation
- https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/57
- https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/51
- Slide Template Design (Making Intersect design work)

**Comment by whitevo** [comment]
The intersect Staff said they didn't know how to register for Town Halls and the Workgroups.
We shared details of how Zoom registration works and why we use it with them.

Here are the two different links we use and the registration process is intuitive.
WG Link: https://bit.ly/3W4tb8q
TH Link: https://bit.ly/46nPeKJ

We, as Swarm, do not register other people for Zoom calls.

**Comment by whitevo** [comment]
In July, we continued requesting permission to tag Intersect Members to amplify our outreach messages.
We also requested that they amplify messages for us if we are not allowed to tag everyone.

As of the due date, it still continues to be an issue where our requests do not get a reply.

**Comment by whitevo** [comment]
We started communicating the Town Hall Date change at the 11th July meeting, where we planned actions and next steps with Lara (Head of Community). https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/41

However, through several follow-up reminders, the newsletter date did not change.
That leads to misinformation on when Intersect Town Halls happen.
