### ISSUE TITLE
Intersect Town Hall - Thursday, 29th August 2024

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Intersect-Town-Hall#45]
# Town Hall agenda and planning
- https://docs.google.com/document/d/1fF7ob4gWPgJvPo0M5lXG7v6PZT-DqGjd1sFIZfzghys

# Slides
- https://docs.google.com/presentation/d/1k-MBrrEkao-1Gueo5kY0l676wIvuc4oPuRGKgHkqTCw

# Facilitators
Tevo, Vani and Stephen

# Video
- https://www.youtube.com/watch?v=GurVLmSfs3g

# Meeting Summary Doc
- https://docs.google.com/document/d/1RCOuLRuwBg3xWrX6datkllsrmy-6oZdVwo43Pfz2HGw

# Actions
- [x] Add Agenda Preparation Doc
- [x] Include Slides
- [x] Include Facilitators
- [x] Add Video
- [x] Add Meeting Summary
- [x] Remind Intersect Staff to include Description to their YouTube videos and provide source material

# Other Related Documents
Sheet for collecting timestamps
- https://docs.google.com/spreadsheets/d/1VCAQDpT3vKrqf9MvwoApw5Z9TMkrtiM5PYaK_rfVolg/edit?gid=0#gid=0

> The same source will be used for both TH and ATH timestamps

**Comment by whitevo** [comment]
Improved Call Out for slide creation and posted again in Discord  https://discord.com/channels/1136727663583698984/1245340231482474506/1270082264801349662

Testing shorter Call out to bring attention to Intersect Town Hall stuff in first place
https://discord.com/channels/1136727663583698984/1136727664036692103/1270085069444354193

![Image](https://github.com/user-attachments/assets/6ef1a90a-e218-4806-bc10-4688ef311bb0)

**Comment by whitevo** [comment]
Since low response and no call out permissions in Discord, will now be attempting the spam mode.

Shared the call out in all group related channels

**Comment by whitevo** [comment]
Slide deck request emails sent to all Committees 14.08

Publicity shared 27th and 28th https://docs.google.com/document/d/1_n2cMAk8uhVoNWanUWEMS8AkLxW8EN0uegHiXBvc6XE/edit#heading=h.ycptt3kp3wuw

And here starting drafting TH Summary: https://docs.google.com/document/d/1RCOuLRuwBg3xWrX6datkllsrmy-6oZdVwo43Pfz2HGw/edit

**Comment by whitevo** [comment]
Interset Staff raised a lot of concerns over Town hall and the communications between us.
We found out the expectations for Milestone 1 Framework is different compared to what we proposed.
We organised ATH to gather more community input and helped Intersect staff to get up to speed, you can learn more about it here: https://docs.google.com/document/d/1EfloV-h6VGFzkCeQ9jXX1eStiK-Ec3Qo6nGayi4dikk/edit?usp=sharing

Also in August we had a little more slides from different groups to present
