### ISSUE TITLE
Intersect After Town Hall - Thursday, 29th August 2024

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Intersect-Town-Hall#46]
Topic: What’s Wrong with Town Hall?
Host: Swarm Town Hall Team
Meeting Video: https://youtu.be/N6YIBKzbtgU

# Meeting Summary

# Intersect Town Hall (TH) Feedback
- August TH felt better than previous ones
- As a committee member, I liked the opportunity to share updates in Town Hall
- I think it's a good sign that the tensions people are raising are largely NOT about the Town Hall itself.
- I learned a lot in After Town Hall and was encouraged to return next month
- After Town Hall has been super useful in echoing my own thoughts and exploring new thoughts
- This Town Hall was very successful as it had so much content and After Town Hall has been very valuable for feedback collection

# Who should share updates in Intersect Town Hall?
- Some of the updates Intersect Staff should be sharing about Committees and things that go on around in Intersect
- It would be good if committees take responsibility for having something to say without a dynamic where Intersect says what the agenda will be.

# What do we expect from Town Hall
- Build audience so that we could some point reach a tipping point where the updates could be presented by the community instead of Intersect Staff
- Allow Intersect members to find ways to change the Town Hall agenda.
- This space is for discovery, but having an overarching Agenda would be good to help orient what we are trying to solve
- Allow space for participants to bring their ideas
- Information should flow between the Town Hall Team and Presenters
- Get the first bits of information on how to get Involved
- Get the basics of what is an Intersect
- Start Agenda discussion early in the month

# How could we improve Town Halls?
- Think about action items people could leave with and come back to the next session to finish that conversation
- Expand Town Halls to different time zones to distribute information more widely across different cultures
  - Community Hubs could take the lead on facilitating THs in different time zones
- Town Hall agenda hops around over so many different topics and for a new person, it will be hard to understand how they are all connected
- Have updates ready before the Town Hall week
- The committee are focusing on updating GitBooks, who is responsible getting the key updates from GitBook to Town Hall?
- Share Participation and engagement metrics of the Town Halls
- Have an after-town hall onboarding breakout room
- Maybe we shouldn't have multiple breakout rooms and keep it as a continuation in the main Town Hall?
- Introduce After Town Hall breakout rooms before we get to know each other breakout rooms
-  The community needs to feel that a Town Hall is their platform.
- Have a one pager for Town Hall Framework, currently its all in huge miro board which can be overwhelming: https://miro.com/app/board/uXjVKG5h5BA=/
- Have one meeting with Intersect Staff to review and disseminate the TH WG and asynchronous information several days before Town Hall
- More proactive communication about Town Hall WG
- More proactive announcements about monthly Town Halls
  - Intersect has included links to Town Halls and Town hall Workgroups in Developer Newsletter
- Share Town Hall and Town Hall WG invites through Intersect Twitter
- Improve communication in agreeing on publicity messages
- Expand to multiple platforms where we could share information about Town Halls

# Limitations of current Town hall Framework
- Scarce resources around pulling and formatting Updates together from general updates and Knowledge Base
- Is "townhall" a friendly enough label to encourage people to engage without feeling intimidated?
- We may not have the "appropriate experience" to onboard new people

# Onboarding to Intersect in general
- The Discord is confusing. There are too many channels, and it's hard to find and orient around information. It starts to make sense when you spend a lot of time reading through channels, but it is still overwhelming for most
  - There are multiple support members in Discord answering all kinds of questions and if you have any sort of feedback, you can share it in Discord
  - Through Discord, it is easier to coordinate questions to the right people
  - If you would like to stay anonymous, you can share a direct message to me oso@intersectmbo.org
- Is there a repository of user feedback about onboarding?
  - Depends on where the user is coming from, if its a Website, it has a feedback button at the bottom of the screen
  - You can report any issues or feedback on membership@intersectMBO.org
  - Intersect Staff if collecting that information
  - Town Hall Team has an open Problem Board: https://github.com/orgs/Catalyst-Swarm/projects/2/views/1
- Intersect Staff will run a focus group to improve onboarding next week
- There is educational content coming up from grant teams that help to onboard into Cardano Governance https://intersect.gitbook.io/intersect-community-grants/cohort-3/educational-and-multimedia
- Could we have more general roles in Discord, it makes communication with roles easier and can also be used to reduce the channel amount people see when new people join
- Agree about barriers to participation- a common problem in many chain communities. That is where  Town Halls are a good focus point.
- There will be more signposts, introduction videos and descriptive information on Intersect coming soon from Intersect Staff members
- There should be a place for new members to get onboarded outside the Town Halls as they might feel too intimidating

# How do you get involved as a Haskell Developer?
- I am a Haskell developer and I feel like this Community has also Haskell developers working on open source
  - Here is the Discord Server we have: https://discord.gg/xNUNTBDyfT
  - here is the communication chat we use: irc://irc.libera.chat/#haskell
  - Here is the Matrix channels we use: https://matrix.to/#/#hackage:matrix.org
  - Would be interesting to collaborate and solve open-source Haskell problems
 - We have a Developer experience Group to first connect with with developer advocates that can help coordinate the education and learning efforts
 - If there is strong technical capability, then we have core maintainers with who to coordinate

**Comment by whitevo** [comment]
Drafted Meeting Summary today and edited ATH video. Will work on timestamps later

**Comment by whitevo** [comment]
I went and explored the Discord Server. Its name was Functional Programming.
They do not seem to like Cardano and focus more on trolling new people.

However you might get good programming support
