### ISSUE TITLE
After Town Hall - July 2024 - support and co-facilitation

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Intersect-Town-Hall#47]
- [x] Request submissions for ATH from ODIN
- [x] add Problem Board suggestions
- [x] Documentation of ATH Session organised by @whitevo 

### Deliverable

- https://catalyst-swarm.gitbook.io/intersect-town-hall-playbook/the-proposal/intersect-town-hall-by-swarm

> After TH: 8 ATHs, taking place immediately after each TH. Comprises managing signups for breakout rooms, publicising and outreach, support for people delivering breakout rooms, incentives to key groups to run a regular ATH slot, managing and sharing recordings

### Acceptance Criteria

> After TH: 8 ATHs take place, with at least 3 breakout rooms in each; room hosts report via feedback forms and informal conversations that they felt supported and had everything they needed; any issues are brought to planning meetings and addressed; recordings are uploaded to Youtube and timestamped within 2 weeks; across the 8 months at least some new people who were not previously involved with TH run a breakout room.

### Estimated Duration 

> After TH: 8 months. There will be 8 ATHs, one per month, taking place immediately after the TH session. Recordings from breakout rooms will be uploaded and timestamped within 2 weeks.

### Cost

> After TH: 4,501 ADA The core process of ATH, comprising promotion and publicity, outreach to engage people in running a breakout room, managing signups, offering support such as co-facilitation or help with planning; managing uploads to YouTube and timestamping; and small bounties for particular communities to run a regular ATH slot to build their community, in the manner of LatAm’s Sala de Café in Catalyst.

**Comment by stephen-rowan** [comment]
Text in Newsletter - @VanCardui

> Want to run an Intersect After TownHall?
ATH is the after-party for Town Hall: breakout rooms, run by Intersect members, on topics they care about.

> Next date: Thurs 25th July
> Signup/details: https://forms.gle/69Qp7t49yZDF7R9z5
> Support is available to plan & facilitate - ask in the form! 

Tweet - @Felix-at-Swarm 



![Image](https://github.com/user-attachments/assets/c9990a73-3b86-4389-90c7-ffe6d7e209a4)

**Comment by whitevo** [comment]
Coordinating with Newman about ODIN ATH Session faciliation, summary and timestamping.
Lets see what could be done and how to report results next week

**Comment by whitevo** [comment]
Meeting Summary moved to Swarm Intersect Folder https://docs.google.com/document/d/1TyFomov1K19rBXGdDHHB6SEKwPYpI0NoO2UIaWmb1-I

**Comment by whitevo** [comment]
Newman created template for YT description: https://docs.google.com/document/d/1xbrBF1vTS_juQMRuTmxJkL-SiMLaGVyMVn07Y4kaXeM/edit

Reformated template under Intersect Folder using above draft as base
https://docs.google.com/document/d/173IsSpqkbRN3icXNeyKio7ncwloNZ_oH0UIpGTZQFi0/edit?usp=sharing

**Comment by whitevo** [comment]
The updates from the Problem Board: 

- https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/30#issuecomment-2223297591
