### ISSUE TITLE
A breakout room form is on the Intersect Website that needs come down

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Intersect-Town-Hall#52]
- https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/5

**Comment by whitevo** [comment]
Closing Action to reduce clutter.
The issue continues to be relevant due this day.
Action continues to be in this aggregated list:
- https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/64
