### ISSUE TITLE
Public Intersect Town Hall Planning Workgroup session 1 - Thursday 1st August 2024

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Intersect-Town-Hall#58]
**Intersect Town Hall Workgroup Meeting Overview**
When: **01.08.2024 - 16:00 UTC**
Duration: ~90 min

Zoom: https://bit.ly/3W4tb8q
Proposal: https://bit.ly/3Rct33S
Miro Board: https://bit.ly/4c4Htv0
Context: Workgroup helps to Co-Create and Operate Intersect Town Halls
Parts of Sessions are recorded and uploaded to the Swarm YouTube channel.
Miro Board is used for activities like meeting notes and information collection.

**Suggested Workshop Agendas**
5min - Welcome and Agenda
5min - (Optional) Introductions, Onboarding and Open Questions
15min - Retrospective on July Town Hall
15min - How can we get more people involved?
30min - Next Town Hall agenda and ATH Topic
10min - Open Topics
10min - Next Elegant Steps

## Meeting Notes
- https://miro.com/app/board/uXjVKG5h5BA=/?moveToWidget=3458764595808218396&cot=10

## Deliverables
- August Town Hall Meeting Agenda https://docs.google.com/document/d/1fF7ob4gWPgJvPo0M5lXG7v6PZT-DqGjd1sFIZfzghys

**Comment by whitevo** [comment]
I recently removed my assignment status, it is unclear to me what that represents

I was able to join a session and took meeting notes, but we agreed that no summary or follow up is needed from me https://miro.com/app/board/uXjVKG5h5BA=/?moveToWidget=3458764595808218396&cot=10

I did complete the action item "Submit call out in every channel" Example of message: https://discord.com/channels/1136727663583698984/1201446491517108254/1270628320844845067

**Comment by whitevo** [comment]
the session happened and was faciliated by Tevo
