### ISSUE TITLE
Public Intersect Town Hall Planning Workgroup session 2 - Thursday 8th August 2024

### ISSUE THREAD

**Issue by stephen-rowan** [Catalyst-Swarm/Intersect-Town-Hall#59]

**Comment by stephen-rowan** [comment]
- https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/27

**Comment by VanCardui** [comment]
Finalised survey.
Vani to contact Lara to make absolutely certain we don't have permission to use Intersect's contact list to send it out.
Assuming not, we will focus on reaching people who are already active in Intersect's Discord, but do not attend TH.

see 

- https://github.com/Catalyst-Swarm/Intersect-Town-Hall/issues/27
