### ISSUE TITLE
Need more publicity for Town Hall

### ISSUE THREAD

**Issue by VanCardui** [Catalyst-Swarm/Intersect-Town-Hall#61]
We need to think more about how and where to publicise 
- Town Hall itself
- requests for info from working groups and special interest groups
- requests for people to run an ATH

and try to make publicity regular and co-ordinated

**Comment by VanCardui** [comment]
### Channels:
- Intersect newsletter
- Discord
- Twitter
- Cardano forum?

### Actions
Ask Intersect team to include an item reminding people of the date of TH and the link to it in subsequesnt newsletters.We could include a graphic about the agenda - could be taken direct from the slides, for example https://docs.google.com/presentation/d/1kczrgQ0tnQcrVN0g8k9Sqpgz0x6BzEzCo3GgD4zZZY8/edit?usp=sharing

Post this slide in Discord, and Tweet it

Repeat our Tweet inviting ATH signups

**Comment by VanCardui** [comment]
Need to create a workflow to ensure newsletter text is written and sent each week after planning WG or internal team meeting

**Comment by whitevo** [comment]
Here is the task that runs across the entire project and includes different tools and methods we have been using to publicise information
https://github.com/orgs/Catalyst-Swarm/projects/1/views/1?pane=issue&itemId=62973624&issue=Catalyst-Swarm%7CIntersect-Town-Hall%7C8
