### ISSUE TITLE
Intersect After Town Hall - Thursday, 26th September 2024 - room 1

### ISSUE THREAD

**Issue by whitevo** [Catalyst-Swarm/Intersect-Town-Hall#69]
Each ATH room will have its own summary

### Topic
> DRep Q&A

### Description
> We are educating the Cardano community on the Cardano DRep processes.

### Host
> DRep Chain

### Meeting Video
> https://youtu.be/c1pND8fvFd0

## Action Items
- [x] Faciliation
- [x] Meeting Summary
- [x] Short Description for the video
- [x] Timestamps
> https://docs.google.com/spreadsheets/d/1VCAQDpT3vKrqf9MvwoApw5Z9TMkrtiM5PYaK_rfVolg
- [ ] (Optional) Publicity

## Discussion Pundits:
- Nana Safo
- Tevo Saks
- Seidu Ziblim 
- Brian Hughes
- Daniel Effiom
- Fidelia Ayaabilla
- Eduardo Fereira

# Meeting Summary

Significantly, the meeting focused on the current and proposed voting system which is "one lovelace equals one vote". Participants explored reforms, including the possibility of capping delegation amounts to prevent the centralization of voting power. The goal is to ensure a fairer distribution of governance influence across the ecosystem.

Concerns about potential excessive delegation to a single DRep raised the need for caps on delegation size. This would prevent one entity from gaining overwhelming influence and ensure a more balanced governance model.

The discussion progressed to whether DReps should be financially incentivized. The pundits felt DReps deserved compensation for their time and efforts, but the reward system must be carefully designed to avoid corrupt practices or misaligned incentives.

The discussion concluded with the pundits discussing what one would like to see in a DRep pool before delegating to them. The discussion largely favored team-based DReps over individual representatives, believing teams offer better decision-making, accountability, and governance oversight. The need for more structured governance workshops and training was also discussed to support the evolution of Cardano’s governance framework.

**Comment by NanaSafo01** [comment]
Meeting Summary: https://docs.google.com/document/d/1iHgCGCsya0SWKlXC47olySI2XUxAqiKqPTUzF9p4LRA/edit?usp=sharing

**Comment by NanaSafo01** [comment]
Meeting Description: In this episode, we discuss essential topics surrounding the Cardano Voltaire DRep process. It is hosted by DRep Chain.

**Comment by NanaSafo01** [comment]
**Timestamp**
Introduction: 00:00 https://youtu.be/c1pND8fvFd0

DRep Voting System: 10:13 https://youtu.be/c1pND8fvFd0?t=613

Delegation Cap for DReps?: 31:20 https://youtu.be/c1pND8fvFd0?t=1880

Should we have a Cap on total DReps?: 39:36 https://youtu.be/c1pND8fvFd0?t=2376

DRep voting rewards and how one would select a DRep: 42:27 https://youtu.be/c1pND8fvFd0?t=2547

Conclusion: 54:52 https://youtu.be/c1pND8fvFd0?t=3292
