### ISSUE TITLE
Intersect After Town Hall - Thursday, 26th September 2024 - room 2

### ISSUE THREAD

**Issue by whitevo** [Catalyst-Swarm/Intersect-Town-Hall#73]
Each ATH room will have its own summary

### Topic
> Marketing Working Group

### Description
> Shares update on the budget version and the charter. Find answers to the following question: "How should Marketing WG share its decision with the community?"

### Host
> Ginatama and LeBlanc

### Meeting Video
> https://youtu.be/3_Vc0zWTy6E

## Action Items
- [x] Faciliation
- [x] Meeting Summary
- [x] Short Description for the video
- [x] Timestamps
> https://docs.google.com/spreadsheets/d/1VCAQDpT3vKrqf9MvwoApw5Z9TMkrtiM5PYaK_rfVolg
- [ ] (Optional) Publicity

## Meeting Administration
Hosts:
- Martin
- Gintama

Co-Hosts:
- Seomon

Participants:
- Martin
- Gintama
- Seomon
- Zain Khan
- Eduardo Ferreira
- AF

# Meeting Summary

This document summarizes the key points from the Cardano Marketing Working Group meeting held after the Town Hall on September 26th.

## Introduction:
The Marketing Working Group was formed to address the lack of marketing support for Cardano products and projects.
The group aims to improve Cardano's onboarding process by attracting new users through effective marketing.

## Group Activities:
Drafted a MWG budget proposal (Version 1) submitted to the budget committee for review. 
Developed a marketing intake form to recruit members with relevant expertise.
Created a group charter to outline the group's goals and activities.

## Discussion Topic:
How can the Marketing Working Group effectively communicate its work and outputs to the Cardano community?

## Action Items:
Review the MWG budget proposal (Version 1) and share feedback.
Join the Marketing Working Group Discord server and fill out the intake.
Attend the next Marketing Working Group meeting tomorrow to participate in the champion election.
Share suggestions in the chat for effective communication strategies with the Cardano community.

All referred documents are available here:
https://linktr.ee/Intersect_Marketing_WG

## Footnote
Author: Martin Marinov, Marketing Specialist, Intersect MBO
Document: Marketing Working Group Meeting Minutes
Date: September 29, 2024

**Comment by Martin-Marinovv** [comment]
Finalized Minutes Meeting for the Intersect After Town Hall MWG meeting on 26th of September

https://drive.google.com/drive/folders/1ep0HaB42mnk4jInYwxq6A4tta7GcPfi2?usp=sharing)

**Comment by whitevo** [comment]
I updated the main GitHub description with the meeting summary and added timestamps to the published video.
